api/urls.py
from django.urls import path, include

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views



app_name = 'api'

urlpatterns = [
    path('', views.api_root),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('slugs/', views.SlugList.as_view(), name='slug_list'),
    path('slugs/<slug:pk>/', views.SlugDetail.as_view(), name='slug_detail'),
]

config/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

urlpatterns = [
    path('schema', get_schema_view(
        title='UrlButcherAPI',
        description='API for the urlbutcher'
        ),
        name='openapi-schema'
    ),
    path('docs/', include_docs_urls(title='UrlButcherAPI')),
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('', include('urlbutcher.urls')),
]

urlbutcher/urls.py
from django.urls import path, re_path, include

from . import views



app_name = 'urlbutcher'

urlpatterns = [
    re_path(r'^$|home/', views.home, name='home'),
    path('slug/', include([
        path('new', views.create_short_slug, name='create_short_slug'),
        path('funny', views.create_funny_slug, name='create_funny_slug'),
        path('chuck', views.create_chuck_norris_slug, name='create_chuck_slug'),
        path('reset_history', views.reset_cookie_last_slugs, name='reset_cookie_last_slugs'),
        path('refresh/<slug:slug_id>/', views.refresh_slug, name='refresh_slug'),
        path('edit/<slug:slug_id>/', views.edit_slug, name='edit_slug'),
        path('delete/<slug:slug_id>/', views.delete_slug, name='delete_slug'),
        path('dashboard', views.dashboard, name='dashboard'),
    ])),
    path('<slug:slug_id>/', views.redirect_slug, name='redirect_slug'),
]

templates/alert.html
{% if messages %}
  {% for msg in messages %}
  <div class="alert {{ msg.level_tag }} alert-dismissible fade show shadow text-wrap"
      role="alert">
    {{ msg }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
{% endif %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% include 'meta.html' %}
    <title>URL.Bu..tcher</title>
  </head>
  <body>
    {% include 'nav.html' %}
    <div class="container-md mb-5 px-0 shadow">
      <div class="mb-5 p-5 bg-light text-center">
        <h1 class="display-4">Let <b>URL.Bu..tcher</b> do his work!</h1>
        <p class="lead">A URL shortener to help you share links with your friends.</p>
        <hr class="my-4">
      </div>
    </div>
    <div class="container-md mb-5">{% include 'alert.html' %}</div>
    <div class="container-md mb-5 px-0 p-5 shadow">
      {% block content %}{% endblock content %}
    </div>
    {% include 'scripts.html' %}
  </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="card border-0 mx-auto col-xl-10">
  <div class="card-body">
    <p class="h4">Your slugs</p>
    <ul class="list-group mt-3">
      {% for slug_item in user_slugs %}
      <li class="list-group-item d-flex flex-wrap justify-content-between align-items-center">
        <a class="text-truncate link-primary" title="{{ slug_item.url }}" target="_blank"
            href="{% url 'urlbutcher:redirect_slug' slug_item.slug %}">
          {% if slug_item.expired %}
            <s class="link-secondary">{{ slug_item.slug }}</s>
          {% else %}
            {{ slug_item.slug }}
          {% endif %}
        </a>
        <sub class="text-muted">{{ slug_item.created_at }}</sub>
        <span>
          <span class="badge bg-light">
            <span class="badge bg-primary rounded-pill">{{ slug_item.counter.click_counter}}</span>
            <sub class="text-black-50">clicks</sub>
          </span>
          <form class="d-inline-block" action="{% url 'urlbutcher:refresh_slug' slug_item.slug %}" method='post'>
            {% csrf_token %}
            <button type="submit" class="btn btn-sm bg-secondary" title="refresh expiry date">
              <i class="fa fa-refresh text-white"></i>
            </button>
          </form>
          <a class="btn btn-sm bg-info text-light" href="{% url 'urlbutcher:edit_slug' slug_item.slug %}">
            Edit
          </a>
          <button class="btn btn-sm bg-danger text-light delete-slug" data-id="{{ slug_item.slug }}">
            Delete
          </button>
        </span>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
<script type="text/javascript">

var csrftokenInput = '{% csrf_token %}'
var deleteBtns = document.querySelectorAll('.delete-slug')
deleteBtns.forEach(item => {
  item.addEventListener('click', () => {
    confirm_delete(item.dataset.id)
  })
})

function confirm_delete(slug_id) {
  swal.fire({
    title: 'Confirmation',
    text: 'Are you sure?',
    icon: 'warning',
    confirmButtonText: 'Yes, delete it.',
    confirmButtonColor: '#dc3545',
    showCancelButton: true,
    cancelButtonColor: '#adb5bd',
    reverseButtons: true,
  })
  .then(result => {
    if (result.isConfirmed) {
      var form = document.createElement('form')
      form.action = `/slug/delete/${slug_id}/`
      form.method = 'post'
      form.innerHTML = csrftokenInput
      document.body.appendChild(form)
      form.submit()
    }
  })
}

</script>
{% endblock content %}

templates/edit_slug.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<div class="card border-0 mx-auto col-xl-10">
  <div class="card-body">
    <form class="row g-3 align-items-center" action="" method="post">
    {% csrf_token %}
    {% for field in form %}
      {% if fields.errors %}
        {% render_field field class="form-control form-control-lg is-invalid" %}
        {% for err in field.errors %}
        <div class="invalid-feedback">
        {{ err }}
        </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control form-control-lg" %}
      {% endif %}
    {% endfor %}
    <input class="btn btn-primary" type="submit" value="Apply"/>
    <a class="btn btn-secondary link-white" href="{% url 'urlbutcher:dashboard' %}">Cancel</a>
    </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<div class="card border-0 mx-auto col-xl-10">
  <div class="card-body">
    <form class="row g-3 align-items-center was-validated" method="post">
      {% csrf_token %}
      {% if form.slug.value == None or form.is_bound %}
        {% for field in form.visible_fields %}
          <div class="mb-3">
          {% if field.errors %}
            {% render_field field class="form-control form-control-lg is-invalid" %}
            {% for err in field.errors %}
            <div class="invalid-feedback">
              {{ err }}
            </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control form-control-lg" %}
          {% endif %}
          </div>
        {% endfor %}
        <div class="col-md-4">
          <input type="submit" class="btn btn-primary btn-block" formaction="{% url 'urlbutcher:create_short_slug' %}" value="Shorten"/>
        </div>
        <div class="col-md-4">
          <input type="submit" class="btn btn-dark btn-block" formaction="{% url 'urlbutcher:create_funny_slug' %}" value="Get Funny Link"/>
        </div>
        <div class="col-md-4">
          <input type="submit" class="btn btn-dark btn-block" formaction="{% url 'urlbutcher:create_chuck_slug' %}" value="Get Chuck Link"/>
        </div>
      {% else %}
        <div class="mb-3">
          {% render_field form.slug class="form-control form-control-lg" %}
          {{ form.slug.errors }}
        </div>
        <div class="col-md-4">
          <input type="button" class="btn btn-primary btn-block" id="copy-slug" value="Copy"/>
        </div>
        <div class="mb-3">
          <small>
            <a class="form-text text-muted" href="{%url 'urlbutcher:home' %}">
              Shorten another link
            </a>
          </small>
        </div>
      {% endif %}
    </form>
  </div>
</div>
<!-- last slugs -->
{% if last_slugs %}
<div class="card border-0 mx-auto col-xl-10">
  <div class="card-body">
    <ul class="list-group">
      {% for slug in last_slugs %}
      <li class="list-group-item d-flex flex-wrap justify-content-between">
        <span>{{slug.0}}</span>
        <span class="text-truncate">
          <a class="list-group-item-action list-group-item-light" href="{{slug.1}}">{{slug.2}}</a>
        </span>
      </li>
      {% endfor %}
    </ul>
    <form action="{% url 'urlbutcher:reset_cookie_last_slugs' %}" method='POST'>
      {% csrf_token %}
      <input class="mt-3 btn btn-sm btn-link text-info" type="submit" value="Reset history"/>
    </form>
  </div>
</div>
{% endif %}
{% endblock content %}

templates/meta.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous"/>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<link rel="stylesheet" href="{% static '/css/styles.css' %}"/>

templates/nav.html
<nav class="navbar sticky-top navbar-dark navbar-expand-md mb-2 bg-secondary bg-gradient shadow-sm">
  <div class="container-md text-white-50 justify-content-between">
    <a class="navbar-brand" href="{% url 'urlbutcher:home' %}">URL.Bu..tcher</a>
    {% if request.user.is_authenticated %}
    <span>
      <a class="btn btn-outline-warning border-0" href="{% url 'urlbutcher:dashboard' %}">
        Dashboard
      </a>
      <a class="btn btn-outline-light border-0" href="{% url 'logout' %}">Sign Out</a>
    </span>
    {% else %}
    <span>
      <a class="btn btn-outline-light border-0" href="{% url 'login' %}">Sign In</a>
      <a class="ml-1 btn btn-outline-light border-0" href="{% url 'register' %}">Sign Up</a>
    </span>
    {% endif %}
  </div>
</nav>

templates/scripts.html
<script type="text/javascript">

// Copy generated `slug` to clipboard:
const copyBtn = document.querySelector('#copy-slug')
if (copyBtn) {
  copyBtn.addEventListener('click', () => {
    navigator.permissions.query({name: "clipboard-write"}).then(result => {
      if (result.state == "granted" || result.state == "prompt") {
        navigator.clipboard.writeText(
          document.querySelector('#{{form.slug.auto_id}}').value
        )
      }
    })
  })
}

</script>